### ISSUE TITLE
s6-overlay-suexec: fatal: can only run as pid 1

### ISSUE THREAD

**Issue by zSprawl** [PecceG2/Home-Assistant-SNMP-Sensor-Server#1]
Getting the following error on startup"

> s6-overlay-suexec: fatal: can only run as pid 1

It likely has to do with this post, but I don't understand. 

https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/

Any ideas?

**Comment by PecceG2** [comment]
Hi! A new version was uploaded that should fix the problem you're having.
Could you check if the problem continues?

**Comment by zSprawl** [comment]
Worked perfectly. 

I couldn't figure out how to inject the init command, but now I see how you've done it. Thanks for the quick turn around!!
