### ISSUE TITLE
snmp service wont start : This environment is externally managed

### ISSUE THREAD

**Issue by rschitz** [PecceG2/Home-Assistant-SNMP-Sensor-Server#4]
on fresh haos_ova-11.4.ova install

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[10:17:10] INFO: Preparing SNMP Sensor Server, please wait..
[10:17:10] INFO: Generating OID for HA sensors..
error: externally-managed-environment

× This environment is externally managed
╰─> 
    The system-wide python installation should be maintained using the system
    package manager (apk) only.
    
    If the package in question is not packaged already (and hence installable via
    "apk add py3-somepackage"), please consider installing it inside a virtual
    environment, e.g.:
    
    python3 -m venv /path/to/venv
    . /path/to/venv/bin/activate
    pip install mypackage
    
    To exit the virtual environment, run:
    
    deactivate
    
    The virtual environment is not deleted, and can be re-entered by re-sourcing
    the activate file.
    
    To automatically manage virtual environments, consider using pipx (from the
    pipx package).

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by mar-svo** [comment]
Hello, I have same problem.
Possibly cause: https://github.com/PecceG2/Home-Assistant-SNMP-Sensor-Server/blob/7cec1b62360f727c217e07a5410aed32081da415/data/run.sh#L18C15-L18C23 -> "pip3 install requests" .. it should be in Dockerfile ?

**Comment by PecceG2** [comment]
Hi! This issue has been resolved in #e1ba451
Please, update addon and try again.

Greetings.-

**Comment by rschitz** [comment]
Hi, thanks a lot, it now works great!
