### ISSUE TITLE
Allow scoping what sensors are exposed 

### ISSUE THREAD

**Issue by JacobErnst98** [PecceG2/Home-Assistant-SNMP-Sensor-Server#7]
If you have a lot of sensors in HA an snmpwalk of the OID for sensors can take an extremely long time. 

Allowing scoping of individual entities or even just domains would reduce the amount of data exposed over SNMP, improving performance and security.

**Comment by PecceG2** [comment]
Hi @JacobErnst98, ¿How are you?
I really liked your idea, and I was having the same problem with so many sensors out there.
Added a field in the config called "`sensors_to_expose`" which you can add a comma separated list of sensors you want to expose (And it supports wildcards with *****!).

Examples:
`light.mylight, light.mylight2`
`sensor.*, light.mylight2`
`light.*`
`light.bathroom*`
`all` (expose all entities in ha)


Remember to update to version **1.4.3** to see this setting available.

**Comment by JacobErnst98** [comment]
@PecceG2 Thank you! 
Working Perfectly!
